services:
  # PostgreSQL Database
  postgres:
    image: postgres
    container_name: dev_postgres
    environment:
      POSTGRES_DB: TransitData
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network

  # Redis Cache
  redis:
    image: redis
    container_name: dev_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev_network

volumes:
  postgres_data:
  redis_data:

networks:
  dev_network:
    driver: bridge